# Generated by Django 3.2.6 on 2021-08-28 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='BookHunter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='WrittenBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookedex_api.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookedex_api.book')),
            ],
        ),
        migrations.CreateModel(
            name='WantedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookedex_api.book')),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookedex_api.bookhunter')),
            ],
        ),
        migrations.CreateModel(
            name='CollectedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookedex_api.book')),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookedex_api.bookhunter')),
            ],
        ),
    ]
