# Generated by Django 3.2.6 on 2021-08-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookedex_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(default='bla', max_length=45),
            preserve_default=False,
        ),
    ]
